### ISSUE TITLE
Can't save text edit in common pokemon SW

### ISSUE THREAD

**Issue by Dalk2ness** [kwsch/pkNX#343]
i got jit error when i try to save text edit.

```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at pkNX.Structures.TextFile.GetVariableParameters(ReadOnlySpan`1 text) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 420
   at pkNX.Structures.TextFile.GetVariableValues(ReadOnlySpan`1 variable) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 377
   at pkNX.Structures.TextFile.GetLineData(ReadOnlySpan`1 line) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 199
   at pkNX.Structures.TextFile.ConvertLinesToData(String[] value) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 159
   at pkNX.Structures.TextFile.set_Lines(String[] value) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 147
   at pkNX.Structures.TextFile..ctor(IEnumerable`1 lines, TextConfig config, Boolean remapChars) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 46
   at pkNX.Structures.TextFile.GetBytes(IEnumerable`1 lines, TextConfig config, Boolean remapChars) in D:\a\1\s\pkNX.Structures\Text\TextFile.cs:line 446
   at pkNX.WinForms.TextContainer.Save() in D:\a\1\s\pkNX.WinForms\Subforms\TextContainer.cs:line 46
   at pkNX.WinForms.TextEditor.B_Save_Click(Object sender, EventArgs e) in D:\a\1\s\pkNX.WinForms\Subforms\TextEditor.cs:line 347
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Private.CoreLib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/pkNX.dll
----------------------------------------
PresentationFramework
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/WindowsBase.dll
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.dll
----------------------------------------
System.Xaml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Xaml.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Threading.Thread.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Windows.Forms.Primitives.dll
----------------------------------------
System.IO.Packaging
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.IO.Packaging.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Private.Uri.dll
----------------------------------------
PresentationCore
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/PresentationCore.dll
----------------------------------------
DirectWriteForwarder
    Assembly Version: 7.0.0.0
    Win32 Version: 7,0,1023,36404 @Commit: 9a9892f5204f1a1b31ab2c81b025d6e35e0f3693
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Diagnostics.Debug.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Threading.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Win32.Registry.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Collections.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Collections.Specialized.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Memory.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Linq.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Drawing.Primitives.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Threading.ThreadPool.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/System.Windows.Extensions.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.ComponentModel.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Collections.Concurrent.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.ObjectModel.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Net.WebHeaderCollection.dll
----------------------------------------
FontAwesome.Sharp
    Assembly Version: 6.3.0.0
    Win32 Version: 6.3.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/FontAwesome.Sharp.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/UIAutomationTypes.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Diagnostics.Process.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/PresentationFramework.Aero2.dll
----------------------------------------
PKHeX.Drawing.PokeSprite
    Assembly Version: 23.2.27.0
    Win32 Version: 23.2.27.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/PKHeX.Drawing.PokeSprite.dll
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/pkNX.Structures.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Text.Json.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Text.Encodings.Web.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Numerics.Vectors.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/UIAutomationProvider.dll
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/pkNX.Game.dll
----------------------------------------
pkNX.Containers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/pkNX.Containers.dll
----------------------------------------
FlatSharp.Runtime
    Assembly Version: 7.2.3.0
    Win32 Version: 7.2.3
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/FlatSharp.Runtime.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Xml.XmlSerializer.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Runtime.Loader.dll
----------------------------------------
pkNX.Randomization
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NSW%20CFW/pkNX/pkNX/net7.0-windows/pkNX.Randomization.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Reflection.Emit.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Text.RegularExpressions.dll
----------------------------------------
System.Console
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Console.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1023.36405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.10/Accessibility.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1023.36312
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.10/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by Kayden21** [comment]
I had this same thing happen did you ever find a fix?

**Comment by pro100luk** [comment]
@duckdoom4, any updates regarding this issue ?

**Comment by duckdoom4** [comment]
> @duckdoom4, any updates regarding this issue ?

I'm not currently working on pkNX. I'm hoping someone else will pick it up in the meantime. Any programmer who wants to is free to make a PR. We are very open to contributions.

If I get back and it's still not fixed, ofc I'll fix it then.

In the meantime, the error above seems to be related to a parsing error that would occur if a tag (eg. `[var1]`) is incorrect.

**Comment by pro100luk** [comment]
@Dalk2ness , @Kayden21  - I have fixed this issue.
You can download working version from here - https://drive.google.com/file/d/1vgEU26DAwPaOR91CVAX8p5PO_hsG9FJF/view?usp=share_link

**Comment by duckdoom4** [comment]
@pro100luk Please just make a pull request so we can fix it.

I trust that you have the right intentions, but unfortunately (as you can hopefully understand) I can't condone posting links to executables that don't have the source publicized

**Comment by Isol8iv** [comment]
@pro100luk I tried out the link you posted (found it using /events/public), and there's still a problem. The error doesn't appear, and when you go in and out of the common or script editor in one session of pkNX, your changes remain. However, if you save everything, close pkNX, and come back, the text reverts back to before you changed it.

Hope this is ok to post here. I've been having the same issue, and haven't been able to find a solution on the forums or Discord. I was instructed to post a new issue here, but thought I would try finding the link first.

**Comment by kwsch** [comment]
Fixed as of latest commits.

**Comment by Isol8iv** [comment]
Afraid not, still getting an error to do with variables, just a different one: 

![image](https://github.com/kwsch/pkNX/assets/159708742/a4ca50db-9236-4c27-8cf2-7dc340202916)

**Comment by Isol8iv** [comment]
Sorry, but still getting an error to do with variables, just a different one: 

![image](https://github.com/kwsch/pkNX/assets/159708742/a4ca50db-9236-4c27-8cf2-7dc340202916)
